### ISSUE TITLE
errors in console + question

### ISSUE THREAD

**Issue by Exyztence** [JohnnyS/JD_logsV3#11]
First of all, I would like to ask how can I turn off those prints in the console? (screenshot attached)

![image](https://github.com/JohnnyS/JD_logsV3/assets/49649458/1b1279b1-5f9c-4432-9c2c-edbf749379ad)

ERRORS

**First one:**
[    script:JD_logsV3] SCRIPT ERROR: @JD_logsV3/server/main.lua:178: bad argument #2 to 'gsub' (string/function/table expected, got nil)
[    script:JD_logsV3] > handler (@JD_logsV3/server/main.lua:17

**Second one:**
[    script:JD_logsV3] SCRIPT ERROR: @JD_logsV3/server/main.lua:295: attempt to index a nil value (local 'rv')
[    script:JD_logsV3] > userCallback (@JD_logsV3/server/main.lua:295)

**Comment by JohnnyS** [comment]
Try to go to server/main.lua line 102 there should be a print(resp), comment that out and it should not print that anymore. 

1st one might be some error with logging weapons being shot. Is this happening on all weapons or certain weapons? If certain ones you might have to add it in a file somewhere I forgot where specifically.

2nd error is api error, since it doesnt exist anymore it no longer works. It shouldnt affect functionality though, someone is working on trying to fix that error with a PR soon.

**Comment by JohnnyS** [comment]
View PR #3 for any updates
